#!/usr/bin/env bash
# Build and run the Android app, re-applying app.config.ts to android/ first.
#
# `expo run:android` only prebuilds when android/ is missing (ensureNativeProjectAsync
# in @expo/cli): when the directory already exists it returns early and config
# plugins are never re-applied. Everything driven by app.config.ts — android.package,
# versionCode, the adaptive icon, the permissions expo-image-picker strips, the
# status-bar style — then stays frozen at whatever the first prebuild produced,
# while the Gradle build still reports success.
#
# android/ is gitignored and fully generated, so prebuilding on every run is safe
# and idempotent. --no-install is fine because Android prebuild has no pod step:
# it only skips the dependency re-check, and dependencies come from the workspace
# install. --clean is deliberately avoided — it wipes the native directory and
# makes Gradle redo work the incremental build skips, far too slow for the normal
# edit/run loop.
#
# APP_ENV and the .env file are supplied by the calling package.json script, so
# prebuild and run resolve the same variant. Arguments are forwarded to
# run:android only — prebuild takes the same flags for every variant.
#
# Two host requirements are read by Gradle, not set here, because both are
# machine-specific: JAVA_HOME must point at JDK 21 (the default JDK 25 makes
# Gradle fail while resolving the foojay toolchain) and ANDROID_HOME at the SDK
# (Gradle does not probe for it). See README.md > Android.
#
# ABI narrowing (debug only). The prebuild template asks for all four ABIs
# (reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64 in the generated
# gradle.properties) while an install target runs exactly one of them. On the
# arm64-v8a emulator used for this repo that costs 245MB → 87MB of debug APK,
# 39s → 3s of `adb install`, and a cold CMake build of react-native-worklets +
# react-native-reanimated of 187s → 79s.
#
# The narrowing is written into the freshly generated android/gradle.properties
# rather than exported as ORG_GRADLE_PROJECT_reactNativeArchitectures: run:android
# spawns Gradle with an environment of its own, so the property never reaches it
# (measured — an x86_64 request still produced an arm64-only APK), while the same
# env var passed to ./gradlew directly works. android/ is regenerated by the
# prebuild above on every run, so this edits a build artifact, never source.
# Release builds keep every ABI: they are what gets handed to a device this
# script cannot inspect.
set -euo pipefail

# ABIs of every attached target, e.g. "arm64-v8a". Empty when adb is unavailable
# or nothing is attached yet (expo boots an AVD itself in that case).
attached_abis() {
  command -v adb >/dev/null 2>&1 || return 0
  local serial
  for serial in $(adb devices | awk '$2 == "device" { print $1 }'); do
    adb -s "$serial" shell getprop ro.product.cpu.abi 2>/dev/null | tr -d '\r'
  done | sed '/^$/d' | sort -u | paste -sd, -
}

# What an AVD or USB device attached to this host would run. Used when nothing
# is attached yet, which is the common "one command starts the emulator" path.
host_abi() {
  case "$(uname -m)" in
    arm64 | aarch64) printf 'arm64-v8a' ;;
    x86_64 | amd64) printf 'x86_64' ;;
  esac
}

target_abis=
case "${MULTICA_ANDROID_ABIS:-auto}" in
  all) ;; # caller asked for the four-ABI default
  auto)
    case " $* " in
      *" --variant release "*) ;; # distribution build: every ABI stays in
      *)
        target_abis=$(attached_abis)
        [ -n "$target_abis" ] || target_abis=$(host_abi)
        ;;
    esac
    ;;
  *) target_abis="$MULTICA_ANDROID_ABIS" ;; # an explicit list wins
esac

pnpm exec expo prebuild -p android --no-install

if [ -n "$target_abis" ]; then
  gradle_properties=android/gradle.properties
  if [ -f "$gradle_properties" ]; then
    narrowed=$(mktemp)
    sed "s/^reactNativeArchitectures=.*/reactNativeArchitectures=$target_abis/" "$gradle_properties" >"$narrowed"
    mv "$narrowed" "$gradle_properties"
    if grep -q "^reactNativeArchitectures=$target_abis$" "$gradle_properties"; then
      echo "android-run: native ABIs = $target_abis (MULTICA_ANDROID_ABIS=all keeps the four-ABI default)" >&2
    else
      echo "android-run: $gradle_properties has no reactNativeArchitectures line to narrow — building the template default" >&2
    fi
  fi
fi

# `java_home -v 21` silently resolves to a newer JDK when 21 is not registered
# with it; the native CMake configure then fails with an opaque message. Say so
# before Gradle spends minutes getting there.
if [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/java" ]; then
  java_major=$("$JAVA_HOME/bin/java" -version 2>&1 | sed -n '1s/.*version "\([0-9]*\).*/\1/p')
  if [ -n "$java_major" ] && [ "$java_major" != "21" ]; then
    echo "android-run: JAVA_HOME points at JDK $java_major, not 21 — native CMake configure may fail; see README > Android" >&2
  fi
fi

exec pnpm exec expo run:android "$@"
